sudo: false
language: ruby
rvm:
# NOTE: Below we cannot use Ruby 1.8.1 on Travis-CI (no longer supported)
- 1.8.7  # For RMXP & RMVX
- 1.9.2  # For RMVXA
script:
- bundle exec rspec --format documentation --require spec_helper --color
